### ISSUE TITLE
Feedback in a FrameLib network

### ISSUE THREAD

**Issue by arvidtp** [AlexHarker/FrameLib#119]
Hi, I'm trying to keep track of the characteristics of individual FFT bins over time, and I was looking for a way to accumulate values that are the results of tests over time (like frameaccum~ in Max). Eventually it seemed like a fl.store~ / fl.recall~ pair would be the right way to implement this kind of internal feedback, but I can't get it to work. Whenever the fl.store~ gets its input from the fl.+~ that I want to accumulate, it never stores anything. I can store frames in it from another network (if that is the right word) of fl objects with a different scheduler, but I can never seem to store output from my primary network and use it again in the same network.

Is there something I'm missing as to how I would do this? Here's a screenshot of a very basic version of what I'm trying to accomplish. Thanks!

<img width="251" alt="Screenshot 2023-11-05 at 8 03 18 PM" src="https://github.com/AlexHarker/FrameLib/assets/7622262/fc213fca-8b8d-4329-b981-419d3b13b747">

**Comment by AlexHarker** [comment]
The basics are right, but there's one issue that stops this from working. The first time you recall the memory is empty so that fl.+~ can't wrap the input, and outputs a zero length vector as a result. The solution is to use the pad_in mode with fl.+~. That should work, because the input will get padded with zeros

[The /trigger_ins left is not really required because the scheduler for both inputs is the same, so they always trigger together].

There might be some other neat tricks of interest for you here: https://github.com/AlexHarker/HISSTools_Freeze/tree/main/source/_Max_Patch/Version_2

(This is an FFT-based / phase-vocoder freeze)

**Comment by AlexHarker** [comment]
(Also for more general questions - rather than bug reports and feature requests this might be a better place - https://framelib.discourse.group )

**Comment by arvidtp** [comment]
Thanks you for your help Alex! I'll give that a try and I'll direct further questions to a more appropriate venue.
