### ISSUE TITLE
Crash with FrameLib multithreading build

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#33]
I am able to reproduce crashes using a multithreading build from commit below:
**e90ec2c85ce47fa8f768d42ef77583651e63342a**

To reproduce, open the patch and follow the numbered instructions. I am running on Max 8.0.6 on Mojave 10.14.6. Other information is in the patch.
[info.zip](https://github.com/AlexHarker/FrameLib/files/3559397/info.zip)

**Comment by jamesb93** [comment]
A little bit more playing with the patch - the crash does not occur at more 'normal' interval settings. It is worth changing the interval to something higher like 1024 to demonstrate the non-crashing vs crashing points.

**Comment by AlexHarker** [comment]
Thanks - it's a consequence of two threads accessing the local memory allocator at the same time without any protection, which shouldn't be the case - this kind of issue with probably occur at any speed, but is more likely with high speeds.

It is now fixed in 2a16ff6f064bb8b65a39e14d3dde9270bf3d1ea8
