### ISSUE TITLE
fl.change~ object request

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#47]
It would be handy to be able to filter out repeated frames. Is there a way to do this currently? If not, can I suggest an fl.change~ object that only outputs a frame if it is different from the previous?

**Comment by AlexHarker** [comment]
You could test that the realist an fl.==~ operation on two frames summed to the length of the frame on one side. This could give you a 1 / 0 for whether the frame was the same from which you could drive an fl.route~ or similar to let the frame through or not.

**Comment by AlexHarker** [comment]
For @fearn-e:

- this object would need to have an output that sometimes (but not always) triggers. That can be seen in FrameLib_Route::Valve (setInput mode and also the update method).
- then it would need an update Method that figures out if the frame has changed (vs. a stored version - see FrameLib_FrameDelta) and stores the new input at the end.
- If it is the same the update method sets the output not to trigger, otherwise it sets it to trigger
- process will now only run if the input has changed and just needs to copy input to output (there's a special methods for that - see FrameLib_Route::Valve)

**Comment by jamesb93** [comment]
👀

**Comment by fearn-e** [comment]
@AlexHarker Hold on, I just got round to starting this, ran the python script to make a new object, and it says fl.change~.cpp already exists. So I go and have a look, and what do you know.
https://github.com/AlexHarker/FrameLib/blob/main/FrameLib_Objects/Routing/FrameLib_Route.cpp
![image](https://github.com/AlexHarker/FrameLib/assets/130933614/de02fcd3-d4f2-449a-8cac-cb4e85c2114b)

**Comment by AlexHarker** [comment]
Ah yes it would appear that I did do this and then promptly forgot all about it. It *looks* like I actually did the object in full, (including VS project etc.) although I suspect I did not write a helpfile.

Can you look to see if there is a proper helpfile and if not, can you make one and test that the object works...

**Comment by AlexHarker** [comment]
Now included in develop at dad4dcb4550158f057ec81aaea1f4ff02e06409c.
