### ISSUE TITLE
fl.getparam~ constantly fires

### ISSUE THREAD

**Issue by jamesb93** [AlexHarker/FrameLib#55]
As far as I can tell, "only the first trigger input" should make fl.getparam~ extract the parameter information from the connected object. In this small patch, it seems fl.getparam~ constantly filres when it is allegedly triggered by fl.once~ but is connected to fl.interval~

<pre><code>
----------begin_max5_patcher----------
531.3ocyVF0iiBBDG+Y8SAgm8ZDrZs2WkKa1fVNO1XAChc6lM69Y+vQ8p2c1
JI0Z1GJFnCye9wLLv69d3L0YdMF8czOPddu664AC0NfWeeO7Q147RVMXFV1b
LiqwAc+UEyj+Kgr3YMO2z4FZDcSX.ZaXb6m3v1VZzlPzS8yw5AUioja.GR6G
saHyaU7N2fwAHbFSVf+yDEGfUfJ6kuQ2eYEnYG4Ft9YtjkUByN7hRB4fPj1w
9v2usIvQXMphBqKuAr62OBV51g1q.K4ZvJjlo4LdU3b1fJIIdDmIzGSPkrNv
xe0p1fTF9YfQ7OK2XTVC+b9vcTRnSaCWMbOI9jT7WAD6N99fPb2WAD6SlePH
lrBHpj4bGHjR.Bi2trDRWABajFVwmHacQt9DqD0HElZjR5PXk.eHwQyPczsJ
RA+ljdxJP+.12JFuabHNIcQCwqQDtfafx7tjGuCfLkrr4wSBIcDjvrvkB4+9
DIXo1N9eSdspQmOnY+9H5xh8.u1HjLivlFewF6x.QPOM4dqq5zVWcVgZeyzH
iT5C1q7auX89jN0Eoi6L59TJwEkHKgRsNgNWbKcoThLmR6VJklMWLYITx0r9
6VHWz4+Ep6TMqp5DWW2aMngsx0KJ3HQZ.zUH65B0UvZ9Iwf8vcGXl1VvxXqV
0ng0E9bxVb2TU1CWxFQeYSKcVIgphR6CaqqXcf.EO8+v+2vMt8wr
-----------end_max5_patcher-----------
</code></pre>

**Comment by AlexHarker** [comment]
Thanks. fl.getparam~ may not exist for much longer, as it is very hard to support in all possible scenarios correctly, but useful to know it isn't functioning as expected in case it stays.

**Comment by AlexHarker** [comment]
OK - this was a simple error fixed by e3b9ff10e779faa4f7291a6b10cbe35071f931ce.

However, I'm now going to remove the object, as it doesn't solve any real problem (you can always derive values from elsewhere, and the work required to maintain correct functionality under all conditions is too high). Something like this may return at a later stage, but for now it is gone.
