### ISSUE TITLE
i386 error with XCode 11

### ISSUE THREAD

**Issue by weefuzzy** [AlexHarker/FrameLib#77]
Since XCode 11 having i386 in your `ARCHS` produces a hard build error (rather than the warning XCode 10 produced). 

The workaround for now is to edit the `xconfig` file to `ARCHS = x86_64`. I don't know if there's scope to put something conditional in there.

**Comment by AlexHarker** [comment]
I think Xcode 10 is where this starts - I build in Xcode 9. Xcode .xcconfigs are pretty minimal in terms of conditionals, but it might be possible to use the SDK as the conditional.

That said - likely in the not too distant future things will change to a universal binary 2.

**Comment by AlexHarker** [comment]
Yeah - for now this is a manual fix, as the xcconfig can't detect the Xcode version. I'll consider dropping 32 bit support soon, even in the absence of an ARM build, as it seems fairly unnecessary in the modern era, or I could add a config to build with 32bit, which might be a nicer solution - I'll have a thing.

**Comment by AlexHarker** [comment]
The fix for this is on develop which is to remove 32bit builds and build a UB2. I'm closing this now, because I hope that develop will soon be on main, and in the meantime I'd suggest anyone daring enough to build at home should use develop. It's just used for upcoming changes, rather than experimental work (which would go elsewhere)
